#服务配置
server:
  port: 9002
#spring配置
spring:
  #2.数据库连接池
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ihrm?useUnicode=true&characterEncoding=utf8
    username: root
    password:
  #3.JPA
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
jwt:
  config:
    key: saas-hrm